dataset:
  train_path: "data/Door-Classification/OriginalSize/RGB/train"
  val_path: "data/Door-Classification/OriginalSize/RGB/val"
  class_names: ["Closed", "Open", "Semi"]

model:
  input_width: 224
  input_height: 224

training:
  epochs: 2
  learning_rate: 0.00005
  optimizer: "Adam"
  loss: "CrossEntropyLoss"

dataloader:
  batch_size: 32
  shuffle: true
  num_workers: 4
  pin_memory: true
  drop_last: false

seed: 1234
output_path: "output/train/t01"
manifest_path: "output/manifests"